export const GET_NOW_WEATHER_LOADING = "GET_NOW_WEATHER_LOADING";
export const GET_NOW_WEATHER_SUCCESS = "GET_NOW_WEATHER_SUCCESS";
export const GET_NOW_WEATHER_FAILING = "GET_NOW_WEATHER_FAILING";
export const GET_DAYS_WETHER_MAIN_LOADING = "GET_DAYS_WETHER_MAIN_LOADING";
export const GET_DAYS_WETHER_MAIN_SUCCESS = "GET_DAYS_WETHER_MAIN_SUCCESS";
export const GET_DAYS_WETHER_MAIN_FAILING = "GET_DAYS_WETHER_MAIN_FAILING";
export const GET_DAYS_WETHER_LOADING = "GET_DAYS_WETHER_LOADING";
export const GET_DAYS_WETHER_SUCCESS = "GET_DAYS_WETHER_SUCCESS";
export const GET_DAYS_WETHER_FAILING = "GET_DAYS_WETHER_FAILING";
export const SEARCH_CITY_LOADING = "SEARCH_CITY_LOADING";
export const SEARCH_CITY_SUCCESS = "SEARCH_CITY_SUCCESS";
export const SEARCH_CITY_FAILING = "SEARCH_CITY_FAILING";

export const LOADING = "LOADING";
export const SUCCESS = "SUCCESS";
export const FAILING = "FAILING";